version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8006:8006"
    environment:
      - PORT=8006
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=accommodation_booking
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=accommodation_booking
      - POSTGRES_USER=postgres # Explicitly set this for clarity
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
